name: deepflightplan
channels:
  - conda-forge
dependencies:
  #
  - python=3.11
  - pandas
  - tqdm
  - matplotlib
  - pip
  - pip:
    - einops
    - geopy
    - networkx[default]
    - tabulate
    - geojson
    - PyYAML
    - joblib