opt:
  save_dir: runs
  seed: 123
  k_closest_node_from_airport: 10
  num_processes: 32

data:
  datasource:
    args:
      file_path: datasets/lido21/pseudo_enroute_airway.geojson
    name: Lido21EnrouteAirwayDataset
  od_dataset:
    args:
      file_path: datasets/od_pair/pseudo_od_pair.csv
    name: ODAirportDataset

distance:
  name: GeopyGreatCircleDistance

metric:
  name: Hausdorff

algorithm:
    name: nxYen
    args:
      top_k: 100
      weights: ['distance'] # ['distance', 'time']